name: Deploy Frontend

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "**"
          target: "~/angularapp"
          
      - name: Check and Kill Process on Port 4200
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            process_id=$(lsof -t -i :4200)
            if [ -n "$process_id" ]; then
              echo "Killing process on port 4200 (PID: $process_id)"
              kill -9 $process_id
            fi

      - name: Build and Start AngularApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/angularapp/api
            nohup /home/azureuser/.nvm/versions/node/v20.18.0/bin/ng s > ~/angularapp/angularapp.log 2>&1 &